# Generated by Django 4.1.1 on 2022-10-13 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("amount", models.FloatField()),
                ("quantity_sold", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("eggs", "eggs"),
                            ("meat", "meat"),
                            ("milk", "milk"),
                            ("other", "other"),
                        ],
                        max_length=14,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "owner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("amount", models.FloatField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("feeds", "feeds"),
                            ("drugs", "drugs"),
                            ("equipment", "equipment"),
                            ("miscellaneous", "miscellaneous"),
                        ],
                        max_length=14,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "owner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("price_bought_per_one", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("animal_age", models.FloatField()),
                ("created_at", models.DateField(auto_now=True)),
                ("alive", models.BooleanField(default=True)),
                (
                    "owner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
