# Generated by Django 4.1.1 on 2023-01-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animal", old_name="animal", new_name="name",
        ),
    ]
