# Generated by Django 4.1.1 on 2022-10-18 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0002_income_expenses_animal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expenses", old_name="type", new_name="category",
        ),
        migrations.RenameField(
            model_name="income", old_name="type", new_name="category",
        ),
        migrations.RemoveField(model_name="animal", name="name",),
        migrations.AddField(
            model_name="animal",
            name="animal",
            field=models.CharField(
                choices=[
                    ("Chicken", "Chicken"),
                    ("Fish", "Fish"),
                    ("Turkey", "Turkey"),
                    ("Cow", "Cow"),
                    ("Goat", "Goat"),
                    ("Sheep", "Sheep"),
                    ("other", "other"),
                ],
                default=datetime.datetime(2022, 10, 18, 10, 15, 26, 857815),
                max_length=8,
            ),
            preserve_default=False,
        ),
    ]
