# Generated by Django 4.1.1 on 2023-01-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0002_rename_animal_animal_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="animal", name="owner_id",),
        migrations.DeleteModel(name="ChatModel",),
        migrations.RemoveField(model_name="expenses", name="owner_id",),
        migrations.RemoveField(model_name="income", name="owner_id",),
        migrations.DeleteModel(name="Animal",),
        migrations.DeleteModel(name="Expenses",),
        migrations.DeleteModel(name="Income",),
    ]
