# Generated by Django 4.1.1 on 2023-01-29 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0003_remove_animal_owner_id_delete_chatmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(default=None, max_length=100)),
                ("message", models.TextField(blank=True, null=True)),
                ("thread_name", models.CharField(blank=True, max_length=50, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("amount", models.FloatField()),
                ("quantity_sold", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("eggs", "eggs"),
                            ("meat", "meat"),
                            ("milk", "milk"),
                            ("other", "other"),
                        ],
                        max_length=14,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "owner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("amount", models.FloatField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("feeds", "feeds"),
                            ("drugs", "drugs"),
                            ("equipment", "equipment"),
                            ("miscellaneous", "miscellaneous"),
                        ],
                        max_length=14,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "owner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Chicken", "Chicken"),
                            ("Fish", "Fish"),
                            ("Turkey", "Turkey"),
                            ("Cow", "Cow"),
                            ("Goat", "Goat"),
                            ("Sheep", "Sheep"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price_bought_per_one", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("animal_age_at_bought", models.FloatField()),
                ("created_at", models.DateField(auto_now_add=True)),
                ("modified_aat", models.DateField(auto_now=True)),
                ("alive", models.IntegerField()),
                (
                    "owner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
