# Generated by Django 4.1.1 on 2022-11-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0003_rename_type_expenses_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animal", old_name="animal_age", new_name="animal_age_at_bought",
        ),
        migrations.AddConstraint(
            model_name="animal",
            constraint=models.UniqueConstraint(
                fields=("animal", "owner_id"), name="unique config"
            ),
        ),
    ]
