# Generated by Django 4.1.1 on 2022-11-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0004_rename_animal_age_animal_animal_age_at_bought_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="animal", name="unique config",),
    ]
