# Generated by Django 4.1.1 on 2022-11-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0005_remove_animal_unique config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal", name="alive", field=models.IntegerField(),
        ),
    ]
