# Generated by Django 4.1.1 on 2022-11-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0006_alter_animal_alive"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="modified_aat",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="animal",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
