# Generated by Django 4.1.1 on 2022-12-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0007_animal_modified_aat_alter_animal_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(default=None, max_length=100)),
                ("message", models.TextField(blank=True, null=True)),
                ("thread_name", models.CharField(blank=True, max_length=50, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="animal",
            name="animal",
            field=models.CharField(
                choices=[
                    ("Chicken", "Chicken"),
                    ("Fish", "Fish"),
                    ("Turkey", "Turkey"),
                    ("Cow", "Cow"),
                    ("Goat", "Goat"),
                    ("Sheep", "Sheep"),
                ],
                max_length=8,
            ),
        ),
    ]
