# Generated by Django 4.1.1 on 2023-01-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0008_chatmodel_alter_animal_animal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
