# Generated by Django 4.1.1 on 2023-01-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0010_alter_animal_created_at_alter_animal_modified_aat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="animal",
            name="modified_aat",
            field=models.DateField(auto_now=True),
        ),
    ]
